package com.example.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.DecimalMin;

/**
 * Entity class representing a product in the system.
 * Contains information such as name, quantity, price, and category.
 */
@Entity
public class Product {

    /**
     * The unique identifier for the product.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the product. Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The available quantity of the product.
     * Must be zero or greater.
     */
    @Column(nullable = false)
    @DecimalMin(value = "0", message = "Quantity cannot be less than zero")
    private int quantity;

    /**
     * The price of the product.
     * Must be zero or greater.
     */
    @Column(nullable = false)
    @DecimalMin(value = "0", message = "Price cannot be less than zero")
    private double price;

    /**
     * The category to which the product belongs. Cannot be null.
     */
    @Column(nullable = false)
    private String category;

    /**
     * Default constructor.
     * Required by JPA for entity instantiation.
     */
    public Product() {
    }

    /**
     * Parameterized constructor to create a new Product.
     *
     * @param id       the product ID
     * @param name     the name of the product
     * @param quantity the available quantity
     * @param price    the price of the product
     * @param category the category of the product
     */
    public Product(Long id, String name, int quantity, double price, String category) {
        this.id = id;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
        this.category = category;
    }

    /**
     * Gets the product ID.
     *
     * @return the product ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the product ID.
     *
     * @param id the new product ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the product name.
     *
     * @return the product name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the product name.
     *
     * @param name the new product name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the product quantity.
     *
     * @return the available quantity
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the product quantity.
     *
     * @param quantity the new quantity
     */
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /**
     * Gets the product price.
     *
     * @return the price
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the product price.
     *
     * @param price the new price
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * Gets the product category.
     *
     * @return the category
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the product category.
     *
     * @param category the new category
     */
    public void setCategory(String category) {
        this.category = category;
    }
}
